apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolly-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dolly-api
  template:
    metadata:
      labels:
        app: dolly-api
    spec:
      containers:
        - name: dolly-api
          image: andyxuan2010/dolly-api:v1.0
          ports:
            - containerPort: 80